[package]
name = "reporting-on-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
serde= { version="1.0", features=["derive"] }
serde_json = "1.0"
schemars = { version="0.8", features=["derive", "chrono"] }
chrono = { version="0.4", features=["serde"] }